image: node:8.9.4

cache:
  paths:
  - node_modules/

before_script:
  - npm install

build:
  stage: build
  only:
    - master
    - develop
  script:
    - npm run build
    - npm rebuild node-sass --force
    
pages:
  stage: deploy
  script: 
    - npm run build
    - mkdir public
    - cp -r dist/* public/
  artifacts:
    paths:
    - public
  only:
    - develop
